name = "LibPNG"
uuid = "302e2f8f-8d6e-5b9d-87b0-6c7ef3dd6509"
authors = ["Josh Christie <joshua.m.christie@gmail.com>", "Mandeep Bahal <mandeep.bahal@roames.com.au>"]
version = "0.1.0"

[deps]
BinDeps = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"

[compat]
julia = "0.7, 1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
